### ISSUE TITLE
Un-Revert 662a1bc

### ISSUE THREAD

**Issue by michaelphagen** [michaelphagen/ZoomMixer#11]
Calling audio devices without sudo likely works fine, and is preferable. Check on multiple OS versions, then revert 662a1bc48c2d122660224002ef66ec4dc838bc34

**Comment by michaelhagen** [comment]
fixed in 1d0e7a2368fea76b3a2979652dbc0ff3dfb1d4f3

**Comment by michaelphagen** [comment]
resolved via 1d0e7a2368fea76b3a2979652dbc0ff3dfb1d4f3
